import type { Product, Category, ShippingMethod } from '@/types';

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Elettronica',
    slug: 'elettronica',
    description: 'Dispositivi elettronici e accessori',
    parent_id: null,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Abbigliamento',
    slug: 'abbigliamento',
    description: 'Moda uomo e donna',
    parent_id: null,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Casa e Giardino',
    slug: 'casa-giardino',
    description: 'Articoli per la casa',
    parent_id: null,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Libri Digitali',
    slug: 'libri-digitali',
    description: 'eBook e contenuti digitali',
    parent_id: null,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Smartphone Pro Max',
    slug: 'smartphone-pro-max',
    description: "L'ultimo modello di smartphone con fotocamera avanzata, processore velocissimo e batteria a lunga durata. Display AMOLED da 6.7 pollici con refresh rate 120Hz. Resistente all'acqua IP68.",
    price: 899.99,
    compare_at_price: 999.99,
    type: 'physical',
    category_id: 'cat-1',
    sku: 'PHONE-001',
    stock_quantity: 50,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
    images: [
      { id: 'img-1', product_id: 'prod-1', url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600', alt_text: 'Smartphone Pro Max', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-2',
    name: 'Laptop Ultraleggero',
    slug: 'laptop-ultraleggero',
    description: 'Notebook professionale con schermo 14" 4K, 16GB RAM, SSD da 512GB. Perfetto per lavoro e studio. Batteria fino a 12 ore.',
    price: 1299.00,
    compare_at_price: null,
    type: 'physical',
    category_id: 'cat-1',
    sku: 'LAPTOP-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
    images: [
      { id: 'img-2', product_id: 'prod-2', url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600', alt_text: 'Laptop Ultraleggero', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-3',
    name: 'Cuffie Wireless Premium',
    slug: 'cuffie-wireless-premium',
    description: 'Cuffie over-ear con cancellazione attiva del rumore, audio Hi-Fi, 30 ore di autonomia. Comfort superiore per sessioni prolungate.',
    price: 249.99,
    compare_at_price: 299.99,
    type: 'physical',
    category_id: 'cat-1',
    sku: 'AUDIO-001',
    stock_quantity: 100,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
    images: [
      { id: 'img-3', product_id: 'prod-3', url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600', alt_text: 'Cuffie Wireless Premium', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-4',
    name: 'T-Shirt Basic',
    slug: 't-shirt-basic',
    description: 'T-shirt in cotone 100% organico, disponibile in vari colori. Vestibilità regolare, perfetta per ogni occasione.',
    price: 29.99,
    compare_at_price: null,
    type: 'physical',
    category_id: 'cat-2',
    sku: 'TSHIRT-001',
    stock_quantity: 200,
    is_active: true,
    is_featured: false,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
    images: [
      { id: 'img-4', product_id: 'prod-4', url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600', alt_text: 'T-Shirt Basic', position: 0, created_at: new Date().toISOString() },
    ],
    variants: [
      { id: 'var-1', product_id: 'prod-4', name: 'Bianco - S', sku: 'TSHIRT-WH-S', price: null, stock_quantity: 30, attributes: { colore: 'Bianco', taglia: 'S' }, is_active: true, created_at: new Date().toISOString() },
      { id: 'var-2', product_id: 'prod-4', name: 'Bianco - M', sku: 'TSHIRT-WH-M', price: null, stock_quantity: 40, attributes: { colore: 'Bianco', taglia: 'M' }, is_active: true, created_at: new Date().toISOString() },
      { id: 'var-3', product_id: 'prod-4', name: 'Nero - M', sku: 'TSHIRT-BK-M', price: null, stock_quantity: 45, attributes: { colore: 'Nero', taglia: 'M' }, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-5',
    name: 'Jeans Slim Fit',
    slug: 'jeans-slim-fit',
    description: 'Jeans in denim di alta qualità, taglio slim fit moderno. Lavaggio medio, perfetto per un look casual ma curato.',
    price: 79.99,
    compare_at_price: 99.99,
    type: 'physical',
    category_id: 'cat-2',
    sku: 'JEANS-001',
    stock_quantity: 80,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
    images: [
      { id: 'img-5', product_id: 'prod-5', url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600', alt_text: 'Jeans Slim Fit', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-6',
    name: 'Felpa con Cappuccio',
    slug: 'felpa-cappuccio',
    description: 'Felpa confortevole in cotone felpato, perfetta per le giornate fresche. Design moderno con cappuccio regolabile.',
    price: 59.99,
    compare_at_price: null,
    type: 'physical',
    category_id: 'cat-2',
    sku: 'FELPA-001',
    stock_quantity: 120,
    is_active: true,
    is_featured: false,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
    images: [
      { id: 'img-6', product_id: 'prod-6', url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600', alt_text: 'Felpa con Cappuccio', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-7',
    name: 'Set Pentole Antiaderenti',
    slug: 'set-pentole-antiaderenti',
    description: 'Set completo di 8 pentole e padelle con rivestimento antiaderente professionale. Adatto a tutti i piani cottura.',
    price: 149.99,
    compare_at_price: 199.99,
    type: 'physical',
    category_id: 'cat-3',
    sku: 'CUCINA-001',
    stock_quantity: 40,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[2],
    images: [
      { id: 'img-7', product_id: 'prod-7', url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600', alt_text: 'Set Pentole Antiaderenti', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-8',
    name: 'Lampada LED Smart',
    slug: 'lampada-led-smart',
    description: 'Lampada da tavolo intelligente, controllo via app, 16 milioni di colori. Compatibile con Alexa e Google Home.',
    price: 49.99,
    compare_at_price: null,
    type: 'physical',
    category_id: 'cat-3',
    sku: 'LAMP-001',
    stock_quantity: 75,
    is_active: true,
    is_featured: false,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[2],
    images: [
      { id: 'img-8', product_id: 'prod-8', url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600', alt_text: 'Lampada LED Smart', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-9',
    name: 'eBook: Guida al Marketing Digitale',
    slug: 'ebook-marketing-digitale',
    description: 'Manuale completo sul marketing digitale: SEO, social media, advertising e analytics. 300+ pagine di contenuti pratici.',
    price: 19.99,
    compare_at_price: 29.99,
    type: 'digital',
    category_id: 'cat-4',
    sku: 'EBOOK-001',
    stock_quantity: 999,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[3],
    images: [
      { id: 'img-9', product_id: 'prod-9', url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600', alt_text: 'eBook Marketing Digitale', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-10',
    name: 'Corso Video: Programmazione Web',
    slug: 'corso-programmazione-web',
    description: 'Corso completo di programmazione web: HTML, CSS, JavaScript, React. 50+ ore di video con progetti pratici.',
    price: 99.99,
    compare_at_price: 149.99,
    type: 'digital',
    category_id: 'cat-4',
    sku: 'CORSO-001',
    stock_quantity: 999,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[3],
    images: [
      { id: 'img-10', product_id: 'prod-10', url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600', alt_text: 'Corso Programmazione Web', position: 0, created_at: new Date().toISOString() },
    ],
  },
];

export const mockShippingMethods: ShippingMethod[] = [
  {
    id: 'ship-1',
    name: 'Spedizione Standard',
    description: 'Consegna in 5-7 giorni lavorativi',
    price: 5.99,
    estimated_days_min: 5,
    estimated_days_max: 7,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ship-2',
    name: 'Spedizione Express',
    description: 'Consegna in 2-3 giorni lavorativi',
    price: 12.99,
    estimated_days_min: 2,
    estimated_days_max: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ship-3',
    name: 'Consegna il Giorno Dopo',
    description: 'Consegna entro il giorno lavorativo successivo',
    price: 19.99,
    estimated_days_min: 1,
    estimated_days_max: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

// Helper to check if we're in demo mode (no Supabase configured)
export function isDemoMode(): boolean {
  const url = (process.env.NEXT_PUBLIC_SUPABASE_URL || '').trim();
  return !url ||
         url === 'https://placeholder.supabase.co' ||
         url.includes('placeholder');
}

export function getMockProduct(slug: string): Product | null {
  return mockProducts.find(p => p.slug === slug) || null;
}

export function getMockFeaturedProducts(): Product[] {
  return mockProducts.filter(p => p.is_featured);
}

export function getMockProductsByCategory(categorySlug: string): Product[] {
  const category = mockCategories.find(c => c.slug === categorySlug);
  if (!category) return mockProducts;
  return mockProducts.filter(p => p.category_id === category.id);
}
