import type { Product, Category, ShippingMethod } from '@/types';

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Electronic devices and accessories',
    parent_id: null,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Clothing',
    slug: 'clothing',
    description: 'Fashion for men and women',
    parent_id: null,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Home and garden items',
    parent_id: null,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Digital',
    slug: 'digital',
    description: 'eBooks and digital content',
    parent_id: null,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Smartphone Pro Max',
    slug: 'smartphone-pro-max',
    description: 'Latest smartphone with advanced camera, fast processor and long battery life. 6.7 inch AMOLED display with 120Hz refresh rate. IP68 water resistant.',
    price: 899.99,
    compare_at_price: 999.99,
    type: 'physical',
    category_id: 'cat-1',
    sku: 'PHONE-001',
    stock_quantity: 50,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
    images: [
      { id: 'img-1', product_id: 'prod-1', url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600', alt_text: 'Smartphone Pro Max', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-2',
    name: 'Ultralight Laptop',
    slug: 'ultralight-laptop',
    description: 'Professional notebook with 14" 4K screen, 16GB RAM, 512GB SSD. Perfect for work and study. Up to 12 hours battery life.',
    price: 1299.00,
    compare_at_price: null,
    type: 'physical',
    category_id: 'cat-1',
    sku: 'LAPTOP-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
    images: [
      { id: 'img-2', product_id: 'prod-2', url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600', alt_text: 'Ultralight Laptop', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-3',
    name: 'Wireless Headphones Premium',
    slug: 'wireless-headphones-premium',
    description: 'Over-ear headphones with active noise cancellation, Hi-Fi audio, 30 hours battery. Superior comfort for extended sessions.',
    price: 249.99,
    compare_at_price: 299.99,
    type: 'physical',
    category_id: 'cat-1',
    sku: 'AUDIO-001',
    stock_quantity: 100,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
    images: [
      { id: 'img-3', product_id: 'prod-3', url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600', alt_text: 'Wireless Headphones Premium', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-4',
    name: 'Basic T-Shirt',
    slug: 'basic-t-shirt',
    description: '100% organic cotton t-shirt, available in various colors. Regular fit, perfect for any occasion.',
    price: 29.99,
    compare_at_price: null,
    type: 'physical',
    category_id: 'cat-2',
    sku: 'TSHIRT-001',
    stock_quantity: 200,
    is_active: true,
    is_featured: false,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
    images: [
      { id: 'img-4', product_id: 'prod-4', url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600', alt_text: 'Basic T-Shirt', position: 0, created_at: new Date().toISOString() },
    ],
    variants: [
      { id: 'var-1', product_id: 'prod-4', name: 'White - S', sku: 'TSHIRT-WH-S', price: null, stock_quantity: 30, attributes: { color: 'White', size: 'S' }, is_active: true, created_at: new Date().toISOString() },
      { id: 'var-2', product_id: 'prod-4', name: 'White - M', sku: 'TSHIRT-WH-M', price: null, stock_quantity: 40, attributes: { color: 'White', size: 'M' }, is_active: true, created_at: new Date().toISOString() },
      { id: 'var-3', product_id: 'prod-4', name: 'Black - M', sku: 'TSHIRT-BK-M', price: null, stock_quantity: 45, attributes: { color: 'Black', size: 'M' }, is_active: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-5',
    name: 'Slim Fit Jeans',
    slug: 'slim-fit-jeans',
    description: 'High quality denim jeans, modern slim fit cut. Medium wash, perfect for a casual yet polished look.',
    price: 79.99,
    compare_at_price: 99.99,
    type: 'physical',
    category_id: 'cat-2',
    sku: 'JEANS-001',
    stock_quantity: 80,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
    images: [
      { id: 'img-5', product_id: 'prod-5', url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600', alt_text: 'Slim Fit Jeans', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-6',
    name: 'Hoodie',
    slug: 'hoodie',
    description: 'Comfortable fleece cotton hoodie, perfect for cool days. Modern design with adjustable hood.',
    price: 59.99,
    compare_at_price: null,
    type: 'physical',
    category_id: 'cat-2',
    sku: 'HOODIE-001',
    stock_quantity: 120,
    is_active: true,
    is_featured: false,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
    images: [
      { id: 'img-6', product_id: 'prod-6', url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600', alt_text: 'Hoodie', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-7',
    name: 'Non-Stick Cookware Set',
    slug: 'non-stick-cookware-set',
    description: 'Complete set of 8 pots and pans with professional non-stick coating. Suitable for all cooktops.',
    price: 149.99,
    compare_at_price: 199.99,
    type: 'physical',
    category_id: 'cat-3',
    sku: 'KITCHEN-001',
    stock_quantity: 40,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[2],
    images: [
      { id: 'img-7', product_id: 'prod-7', url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600', alt_text: 'Non-Stick Cookware Set', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-8',
    name: 'Smart LED Lamp',
    slug: 'smart-led-lamp',
    description: 'Smart desk lamp, app controlled, 16 million colors. Compatible with Alexa and Google Home.',
    price: 49.99,
    compare_at_price: null,
    type: 'physical',
    category_id: 'cat-3',
    sku: 'LAMP-001',
    stock_quantity: 75,
    is_active: true,
    is_featured: false,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[2],
    images: [
      { id: 'img-8', product_id: 'prod-8', url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600', alt_text: 'Smart LED Lamp', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-9',
    name: 'eBook: Digital Marketing Guide',
    slug: 'ebook-digital-marketing',
    description: 'Complete digital marketing handbook: SEO, social media, advertising and analytics. 300+ pages of practical content.',
    price: 19.99,
    compare_at_price: 29.99,
    type: 'digital',
    category_id: 'cat-4',
    sku: 'EBOOK-001',
    stock_quantity: 999,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[3],
    images: [
      { id: 'img-9', product_id: 'prod-9', url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600', alt_text: 'eBook Digital Marketing', position: 0, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'prod-10',
    name: 'Video Course: Web Development',
    slug: 'course-web-development',
    description: 'Complete web development course: HTML, CSS, JavaScript, React. 50+ hours of video with practical projects.',
    price: 99.99,
    compare_at_price: 149.99,
    type: 'digital',
    category_id: 'cat-4',
    sku: 'CORSO-001',
    stock_quantity: 999,
    is_active: true,
    is_featured: true,
    digital_file_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[3],
    images: [
      { id: 'img-10', product_id: 'prod-10', url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600', alt_text: 'Web Development Course', position: 0, created_at: new Date().toISOString() },
    ],
  },
];

export const mockShippingMethods: ShippingMethod[] = [
  {
    id: 'ship-1',
    name: 'Standard Shipping',
    description: 'Delivery in 5-7 business days',
    price: 5.99,
    estimated_days_min: 5,
    estimated_days_max: 7,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ship-2',
    name: 'Express Shipping',
    description: 'Delivery in 2-3 business days',
    price: 12.99,
    estimated_days_min: 2,
    estimated_days_max: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ship-3',
    name: 'Next Day Delivery',
    description: 'Delivery by next business day',
    price: 19.99,
    estimated_days_min: 1,
    estimated_days_max: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

// Helper to check if we're in demo mode (no Supabase configured)
export function isDemoMode(): boolean {
  const url = (process.env.NEXT_PUBLIC_SUPABASE_URL || '').trim();
  const isValidSupabaseUrl = url.startsWith('https://') && url.includes('.supabase.co');
  return !isValidSupabaseUrl;
}

export function getMockProduct(slug: string): Product | null {
  return mockProducts.find(p => p.slug === slug) || null;
}

export function getMockFeaturedProducts(): Product[] {
  return mockProducts.filter(p => p.is_featured);
}

export function getMockProductsByCategory(categorySlug: string): Product[] {
  const category = mockCategories.find(c => c.slug === categorySlug);
  if (!category) return mockProducts;
  return mockProducts.filter(p => p.category_id === category.id);
}
